name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build and Deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Build the application
        go build -o romplin
        
        # Package all files including static and templates
        tar -czf deploy.tar.gz \
          romplin \
          scripts/* \
          nginx/* \
          static/* \
          templates/*
        
        # Setup SSH and deploy
        echo "$SSH_PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        
        # Copy and extract files
        scp -i deploy_key -o StrictHostKeyChecking=no deploy.tar.gz ubuntu@$EC2_HOST:~
        ssh -i deploy_key -o StrictHostKeyChecking=no ubuntu@$EC2_HOST 'bash -s' << 'ENDSSH'
          cd ~
          tar -xzf deploy.tar.gz
          
          # Setup application directory
          sudo mkdir -p /var/www/romplin.info
          sudo cp -r static templates /var/www/romplin.info/
          sudo cp romplin /var/www/romplin.info/
          sudo chown -R ubuntu:ubuntu /var/www/romplin.info
          
          # Setup nginx
          sudo cp nginx/romplin.conf /etc/nginx/conf.d/
          sudo systemctl restart nginx
          
          # Setup and start application
          sudo systemctl stop romplin || true
          sudo cp scripts/setup.sh /var/www/romplin.info/
          chmod +x /var/www/romplin.info/setup.sh
          cd /var/www/romplin.info && sudo ./setup.sh
ENDSSH
