name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build and Deploy
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Build the application
        go build -o romplin
        
        # Package files
        tar -czf deploy.tar.gz romplin main.go scripts/* nginx/* static/* templates/*
        
        # Setup SSH
        echo "$SSH_PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        
        # Deploy
        scp -i deploy_key -o StrictHostKeyChecking=no deploy.tar.gz ubuntu@$EC2_HOST:~
        ssh -i deploy_key -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "
          cd ~
          tar -xzf deploy.tar.gz
          
          # Stop service
          sudo systemctl stop romplin
          
          # Update application
          sudo rm -rf /var/www/romplin.info/*
          sudo mkdir -p /var/www/romplin.info
          sudo cp -r romplin main.go static templates /var/www/romplin.info/
          sudo chown -R ubuntu:ubuntu /var/www/romplin.info
          
          # Update nginx config
          sudo cp nginx/romplin.conf /etc/nginx/conf.d/
          sudo systemctl restart nginx
          
          # Start service
          sudo systemctl start romplin
          
          # Cleanup
          rm deploy.tar.gz
        "
