# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches: [ main ]

env:
  APP_NAME: romplin.info

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build application
      run: |
        go build -o romplin
        
    - name: Package application
      run: |
        tar -czf deploy.tar.gz romplin scripts/* nginx/*
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Copy files to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ec2-user
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Write the SSH key to a file
        echo "$SSH_PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        
        # Copy files to EC2
        scp -i deploy_key -o StrictHostKeyChecking=no \
          deploy.tar.gz $EC2_USERNAME@$EC2_HOST:~
          
        # Execute deployment script
        ssh -i deploy_key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST '
          sudo systemctl stop romplin || true
          rm -rf ~/romplin.info
          mkdir -p ~/romplin.info
          tar -xzf deploy.tar.gz -C ~/romplin.info
          cd ~/romplin.info
          chmod +x scripts/*
          sudo ./scripts/setup.sh
          rm ~/deploy.tar.gz
        '
